- name: Add application user
  ansible.builtin.user:
    name: roboshop

- name: Remove directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: /app
    state: directory

#- name: Download and extract app content
#  ansible.builtin.unarchive:
#    src: https://roboshop-artifacts.s3.amazonaws.com/{{ component }}.zip
#    dest: /app
#    remote_src: yes

- name: Download and extract app content from Nexus
  ansible.builtin.unarchive:
    src: http://172.31.83.14:8081/repository/{{component}}/{{component}}-{{app_version}}.zip
    dest: /app
    remote_src: yes